# This file provides hardcoded Tamil text overrides for native TTS generation.

TAMIL_MAPPING = {
    "AA-maa": "ஆமா",
    "AAT-tai-yah_poh-druh-dhoo": "ஆட்டைய போடுறது",
    "ADJUST_pun-noong-gah": "அட்ஜஸ்ட் பண்ணுங்க",
    "ADVANCE": "அட்வான்ஸ்",
    "AGREEMENT": "அக்ரீமெண்ட்",
    "Appuram_paakkalaam": "அப்புறம் பாக்கலாம்",
    "BAY-maa-nee": "பேமானி",
    "BOSS_JEE": "பாஸ் / ஜி",
    "CHIN-nah": "சின்ன",
    "DHOO-ruh-mah": "தூரமா",
    "DOOT-too": "டுட்டு",
    "DUB-boo": "டப்பு",
    "Enakku_theriyaadhu": "எனக்கு தெரியாது",
    "Eppadi_irukkeenga": "எப்படி இருக்கீங்க?",
    "Evvalavu_aachu": "எவ்வளவு ஆச்சு?",
    "GAA-lee": "காலி",
    "GATE_kit-tah_vuh-chih-DOONG-goh": "கேட் கிட்ட வச்சிடுங்க",
    "GETH-thoo": "கெத்து",
    "Google_Pay_PUN-noong-gah": "கூகுள் பே பண்ணுங்க",
    "ILL-lah": "இல்ல",
    "IN-jee": "இஞ்சி",
    "ING-gah": "இங்க",
    "ING-gah_nee-ROOT-thoong-gah": "இங்க நிறுத்துங்க",
    "IP-poh": "இப்போ",
    "Idadhu_pakkam": "இடது பக்கம்",
    "JAAS-tee": "ஜாஸ்தி",
    "JILL-noo": "ஜில்லுனு",
    "JUM-moo-noo": "ஜம்முனு",
    "KAA-chul": "காய்ச்சல்",
    "KAA-rum": "காரம்",
    "KAAL": "கால்",
    "KAI-yez-hoot-thoo": "கையெழுத்து",
    "KAY-loong-gah": "கேளுங்க",
    "KOHN-jum": "கொஞ்சம்",
    "KOHN-jum_KUM-mee_PUN-noong-gah": "கொஞ்சம் கம்மி பண்ணுங்க",
    "KOHN-jum_busy-ah_ee-ROOK-kayn": "கொஞ்சம் பிஸியா இருக்கேன்",
    "KOO-pih-doong-gah": "கூப்பிடுங்க",
    "KOOP-pai_KOO-toong-gah": "குப்பை கூட்டுங்க",
    "KOOP-pai_POH-doong-gah": "குப்பை போடுங்க",
    "KUM-mee": "கம்மி",
    "KUT-thee": "கத்தி",
    "Konjam_adjust_pannunga": "கொஞ்சம் அட்ஜஸ்ட் பண்ணுங்க",
    "LOCATION_ah-noo-pih-TAYN": "லோகேஷன் அனுப்பிட்டேன்",
    "LUT-chum": "லட்சம்",
    "MAA-doo": "மாடு",
    "MAA-voo": "மாவு",
    "MAAM-puh-zhum": "மாம்பழம்",
    "MAY-dhoo-vah": "மெதுவா",
    "MIH-luh-gaay": "மிளகாய்",
    "MOH-sum": "மோசம்",
    "MOK-kah": "மொக்க",
    "MOOK-kaal": "முக்கால்",
    "MOON-naa-dee": "முன்னாடி",
    "MUH-nee": "மணி",
    "MUH-rum": "மரம்",
    "MUH-zhai": "மழை",
    "MUN-jul": "மஞ்சள்",
    "NAA-lai-koo_kaa-lai-LAH_VAA-ngah": "நாளைக்கு காலைல வாங்க",
    "NAA-mah": "நாம",
    "NAAN": "நான்",
    "NAAN_call_pun-nee-NAYN": "நான் கால் பண்ணினேன்",
    "NAAN_ing-gah_VAY-lai_paak-koo-RAYN": "நான் இங்க வேலை பாக்குறேன்",
    "NAAN_ip-poh-VAY_vuh-RAYN": "நான் இப்போவே வரேன்",
    "NAAN_poh-RAYN": "நான் போறேன்",
    "NAAY": "நாய்",
    "NAY-rah": "நேரா",
    "NAY-rum": "நேரம்",
    "NEE": "நீ",
    "NEE-lum": "நீளம்",
    "NEE-mee-shum": "நிமிஷம்",
    "NEENG-gah": "நீங்க",
    "NUL-lah": "நல்லா",
    "NUL-lah_ee-ROOK-kayn": "நல்லா இருக்கேன்",
    "Nirutthunga": "நிறுத்துங்க",
    "ONLINE-lah_PAY_pun-nih-TAYN": "ஆன்லைன்ல பே பண்ணிட்டேன்",
    "OO-roo-lai_kih-ZHUNG-goo": "உருளைக்கிழங்கு",
    "OOL-lah_VAA-ngah": "உள்ள வாங்க",
    "OOL-lah_VAY-lee-yah": "உள்ள / வெளிய",
    "OOP-poo": "உப்பு",
    "PAA-thih-rum_kuh-ZHOO-voong-gah": "பாத்திரம் கழுவுங்க",
    "PAAL": "பால்",
    "PAH-ruh-vaa-lah": "பரவால்ல",
    "PAY-roo": "பேரு",
    "PIN-naa-dee": "பின்னாடி",
    "POHN-gah": "போங்க",
    "POO-doo-soo": "புதுசு",
    "POO-nai": "பூனை",
    "POON-doo": "பூண்டு",
    "PUCH-chai": "பச்சை",
    "PUH-roop-poo": "பருப்பு",
    "PUH-ruh-vai": "பறவை",
    "PUH-zhuh-soo": "பழசு",
    "PUK-kuh-thoo-lah": "பக்கத்துல",
    "PUL-loo": "பல்லு",
    "PUN-chur_aay-ee-doo-choo": "பஞ்சர் ஆயிடுச்சு",
    "PUN-noo": "பண்ணு",
    "Pogalaam": "போகலாம்",
    "ROO-see": "ருசி",
    "RUTH-thum_vuh-roo-dhoo": "ரத்தம் வருது",
    "Romba_nandri": "ரொம்ப நன்றி",
    "SAA-dhum": "சாதம்",
    "SCENE_poh-daa-dhah": "சீன் போடாத",
    "SEM-mah_VAY-rah_LEVEL": "செம / வேற லெவல்",
    "SOL-loong-gah": "சொல்லுங்க",
    "SOO-dah": "சூடா",
    "SOOM-maa_ee-ROONG-gah": "சும்மா இருங்க",
    "SOOT-thum": "சுத்தம்",
    "SUH-ree": "சரி",
    "SUK-kuh-rai": "சர்க்கரை",
    "Saappittaachaa": "சாப்பிட்டாச்சா?",
    "Sari": "சரி",
    "Seekkiram_vaanga": "சீக்கிரம் வாங்க",
    "THAH-lah": "தல",
    "THAYNG-gaay": "தேங்காய்",
    "THOH-dai-yoong-gah": "துடையுங்க",
    "THOO-nee_thoh-VAI-yoong-gah": "துணி துவையுங்க",
    "THUH-yeer": "தயிர்",
    "THUM-bee": "தம்பி",
    "THUN-nee": "தண்ணி",
    "THUN-nee_oh-loo-goo-dhoo": "தண்ணி ஒழுகுது",
    "THUP-poo": "தப்பு",
    "THUT-too": "தட்டு",
    "TIME_ee-ROOK-kaa": "டைம் இருக்கா?",
    "TRAFFIC-ah_ee-rook-koo": "ட்ராபிக்கா இருக்கு",
    "Thamizh_pesunga": "தமிழ் பேசுங்க",
    "UH-rah": "அரை",
    "UH-ree-see": "அரிசி",
    "UH-zhook-koo": "அழுக்கு",
    "UNG-gah": "அங்க",
    "VAA-duh-gai": "வாடகை",
    "VAA-ngah": "வாங்க",
    "VAY-guh-mah": "வேகமா",
    "VAY-lai": "வேலை",
    "VAY-lee-yah_NIL-loong-gah": "வெளிய நில்லுங்க",
    "VAY-yeel_SOO-ree-yun": "வெயில் / சூரியன்",
    "VAYN-daam": "வேண்டாம்",
    "VEH-noom": "வேணும்",
    "VEL-lai": "வெள்ளை",
    "Vaanga": "வாங்க",
    "Valadhu_pakkam": "வலது பக்கம்",
    "Vanakkam": "வணக்கம்",
    "Vendaam": "வேண்டாம்",
    "WORK_aa-guh-lah": "ஒர்க் ஆகல",
    "YAA-roo": "யாரு",
    "YAY-maa-thoo-reeng-gah": "ஏமாத்துறீங்க",
    "YEN-nah": "என்ன",
    "YEN-nai": "எண்ணெய்",
    "YENG-gah": "எங்க",
    "YEN_thup-POO_dhaan": "எந்தப் பூ தான்",
    "YEN_thup-POO_ill-lah": "எந்தப் பூ இல்ல",
    "YEP-poh": "எப்போ",
    "a-dhay-LAAM_VAY-naam": "அதெல்லாம் வேணாம்",
    "ah": "ஆ",
    "bay-JAA-roo": "பேஜார்",
    "bis-KOHT-thoo": "பிஸ்கோத்து",
    "car-oo": "காரு",
    "doo-BAAK-koor": "டுபாக்கூர்",
    "ee-NIP-poo": "இனிப்பு",
    "ee-ROO-vuh-thoo_ON-noo": "இருபத்து ஒன்னு",
    "ee-ROOK-koo": "இருக்கு",
    "ee-duh-DHOO_PUK-kum": "இடது பக்கம்",
    "ee-nee-MAY-l_dhaan": "இனிமேல் தான்",
    "eh-nuh-KOO_HELP_veh-noom": "எனக்கு ஹெல்ப் வேணும்",
    "eh-nuh-KOO_VAY-lai_ee-ROOK-koo": "எனக்கு வேலை இருக்கு",
    "eh-nuh-KOO_pih-DIH-koom": "எனக்கு பிடிக்கும்",
    "eh-nuh-KOO_puh-SEE-koo-dhoo": "எனக்கு பசிக்குது",
    "eh-nuh-KOO_they-ree-YOOM": "எனக்கு தெரியும்",
    "eh-nuh-KOO_vuh-lee_ee-ROOK-koo": "எனக்கு வலி இருக்கு",
    "ep-puh-DEE_ee-ROOK-keeng-gah": "எப்படி இருக்கீங்க",
    "kalaaichi-fy": "கலாய்ச்சிஃபை",
    "koh-THUM-mul-lee": "கொத்தமல்லி",
    "koo-DEENG-gah": "குடிங்க",
    "kuh-LUK-kul": "கலக்கல்",
    "kuh-NUK-koo": "கணக்கு",
    "kuh-ROO-vayp-pih-lai": "கருவேப்பிலை",
    "kuh-ROOP-poo": "கருப்பு",
    "kuh-SUP-poo": "கசப்பு",
    "kuhs-MAA-lum": "கஸ்மாலம்",
    "muh-CHAAN_MUH-chee": "மச்சான் / மச்சி",
    "muh-root-thoo-vuh-muh-nai-KOO_POH-ngah": "மருத்துவமனைக்கு போங்க",
    "ng-gah": "ங்க",
    "office-oo": "ஆபீஸு",
    "oh-DUN-jee_poh-choo": "ஒடஞ்சி போச்சு",
    "oh-LOONG-gah_PUN-noong-gah": "ஒழுங்கா பண்ணுங்க",
    "oo": "உ",
    "oo-SHAAR": "உஷார்",
    "oo-duh-NAY_oo-dhuh-vee_THAY-vai": "உடனே உதவி தேவை",
    "pay-REE-yuh": "பெரிய",
    "po-LEES-uh_KOO-pih-doo-vayn": "போலீஸ கூப்பிடுவேன்",
    "poo-LIP-poo": "புளிப்பு",
    "puh-DEENG-gah": "படிங்க",
    "saap-PIH-doong-gah": "சாப்பிடுங்க",
    "saap-pih-TAYN": "சாப்பிட்டேன்",
    "saap-pit-TAAH-chaa": "சாப்பிட்டாச்சா",
    "sih-VUP-poo": "சிவப்பு",
    "soo-RAI-kaay": "சுரைக்காய்",
    "they-ree-YAA-dhoo": "தெரியாது",
    "thuh-LAI_vuh-lee": "தலைவலி",
    "thuk-KAA-lee": "தக்காளி",
    "uh": "அ",
    "uh-DHOO": "அது",
    "uh-NOOP-poong-gah": "அனுப்புங்க",
    "uh-PEET-too": "அபீட்டு",
    "uh-VAH_uh-VUL": "அவ / அவள்",
    "uh-VUN": "அவன்",
    "uh-VUNG-gah": "அவங்க",
    "uh-VUNG-gah_uh-VUR-gul": "அவங்க / அவர்கள்",
    "uh-VUNG-noong-gah": "அவனுங்க",
    "uh-VUR_uh-VUNG-gah": "அவர் / அவங்க",
    "uh-dhee-guh-MAA_pay-SAA-theeng-gah": "அதிகமா பேசாதீங்க",
    "up-PROM": "அப்புறம்",
    "vel-LUH-ree-kaay": "வெள்ளரிக்காய்",
    "veng-GAA-yum": "வெங்காயம்",
    "vuh-luh-DHOO_PUK-kum": "வலது பக்கம்",
    "vuh-nuk-KUM": "வணக்கம்",
    "vuh-zhee_ILL-lah": "வழி இல்ல",
    "yeh-DOONG-gah": "எடுங்க",
    "yeh-LOO-mih-chai": "எலுமிச்சை",
    "yeh-ZHOO-dhoong-gah": "எழுதுங்க",
    "yeh-doot-thoo-KOHNG-gah": "எடுத்துக்கோங்க",
    "yev-vuh-luh-VOO_AAH-choo": "எவ்வளவு ஆச்சு",
}
